### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by LachoCardenas44** [LachoCardenas44/GestionAlmacen.CodigoJava#1]
Acabo de hacer un primer commit con el README, por favor reviselo y me dice como puedo mejorarlo o si lo dejo asi.
Falta el modulo de mi compañero, ahora le asigno la tarea.

**Comment by yosbel-penate** [comment]
Va encaminada la cosa, tengo algunos puntos, no veo uso de interfaces y claramente podrían ser útiles para reducir el acoplamiento entre módulos. Si lo que gestionan son almacenes deberían tener una clase superior que tenga de uno a muchos warehouse. Algunas relaciones fuertes no son necesarias, por ejemplo, si un werehause no tiene locación no desaparece, ya que la relación fuerte implica la existencia de su objeto superior. La multiciplidad no se si en algunos casos no es correcta no se revísenla. Orden está flotando, deben decidir donde se almacena la lista de órdenes, lo mimo con Delivery. Necesito una descripción del funcionamiento del negocio, una general y luego una de cada módulo que van a implementar. Ejemplo en la empresa tal gestiona una serie de almacenes que reciben productos, cuando un camión llega el camionero entrega la tarjeta no sé qué ...... y así en detalles, de acuerdo con los pasos de uso de la aplicación que están haciendo. De tal manera que luego yo seré ese camionero y voy a llegar a vuestra empresa y voy a ir por cada paso que me describan. ¿Que debe definir de cada módulo? Que roles van a interactuar con el mismo. Ejemplo en el módulo creación de orden interactúa la secretaria, en el módulo almacén, el almacenero y claro debe estar reflejado en el módulo de usuarios. ¿Otro detalle por que el módulo ExternalAgent se llama así? ¿Son agentes externos por qué? no trabajan dentro de la empresa?

**Comment by LachoCardenas44** [comment]
Los agentes externos no son plantilla en la empresa , es decir no pertenecen al personal , serían proveedores y clientes. 
Revisaremos todo y lo estaremos arreglando periódicamente.
En cuanto a la descripción del funcionamiento ,no sabía que era tan detallado como el ejemplo que puso del camionero ,lo tendré en cuenta. 
Muchas gracias.

**Comment by LachoCardenas44** [comment]
Ya vi el error que vio con respecto al módulo que se llama ExternalAgents , eso está mal y no me di cuenta , originalmente ahí solo había agentes externos pero ahora están todos los posibles usuarios así que hay que cambiarle el nombre al Módulo

**Comment by yosbel-penate** [comment]
ok buen trabajo
